### ISSUE TITLE
Grocy Integration

### ISSUE THREAD

**Issue by akail** [akail/homeassistant#45]
# Ideas
- [ ] Consume cat food if not extended away
- [ ] Track frozen and vacuum packed meat

# Consumption
Use shell command to call curl
```

shell_command:
  grocy_consume_item: "curl -X POST http://{{server_ip}}:9283/api/stock/products/{{product_id}}/consume -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'GROCY-API-KEY: {{grocy_key}}' -H 'cache-control: no-cache' -d '{ \"amount\": {{amount}},  \"transaction_type\": \"consume\",  \"spoiled\": false }'"
```
# Sensors
```
sensor:
  - platform: rest
    resource: http://127.0.0.1:9283/api/stock/products/52
    headers:
      GROCY-API-KEY: GROCYKEY
    name: Dishwashing Tablets
    value_template: '{{ value_json.stock_amount }}'
    scan_interval: 3600
    json_attributes:
      - last_purchased
 ```

# References
* https://philhawthorne.com/automating-your-shopping-list-with-home-assistant-and-grocy/
